# Generated by Django 4.2.5 on 2023-09-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('high_school_number', models.CharField(max_length=255)),
                ('high_school_gpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('standardized_test_scores', models.CharField(max_length=255)),
            ],
        ),
    ]
