# Generated by Django 4.2.5 on 2023-09-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('student_score', models.FloatField()),
                ('chosen_program', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=255)),
                ('university_grade', models.CharField(max_length=1)),
                ('total_slots', models.IntegerField()),
                ('slots_filled', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUniversityAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_id', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.university')),
            ],
        ),
    ]
