# Generated by Django 4.2.5 on 2023-09-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOfStudy',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Engineering', 'Engineering'), ('Business Administration', 'Business Administration'), ('Biology', 'Biology'), ('Psychology', 'Psychology'), ('History', 'History'), ('Mathematics', 'Mathematics'), ('English Literature', 'English Literature'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Economics', 'Economics'), ('Political Science', 'Political Science'), ('Sociology', 'Sociology'), ('Environmental Science', 'Environmental Science'), ('Art and Design', 'Art and Design'), ('Music', 'Music'), ('Medicine', 'Medicine'), ('Nursing', 'Nursing')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='chosen_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.programofstudy'),
        ),
    ]
